---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
  namespace: istio-system
  name: istio-admin
rules:
  - apiGroups:
      - config.istio.io
    resources:
      - adapters
      - attributemanifests
      - handlers
      - httpapispecbindings
      - httpapispecs
      - instances
      - quotaspecbindings
      - quotaspecs
      - rules
      - templates
    verbs: ["get", "watch", "list"]
  - apiGroups:
      - networking.istio.io
    resources:
      - destinationrules
      - envoyfilters
      - gateways
      - serviceentries
      - sidecars
      - virtualservices
      - workloadentries
    verbs:
      - '*'
  - apiGroups:
      - security.istio.io
    resources:
      - authorizationpolicies
      - peerauthentications
      - requestauthentications
    verbs:
      - '*'
