kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: istio-installer
subjects:
- kind: ServiceAccount
  name: serviceaccount
  namespace: istio-system
roleRef:
  kind: ClusterRole
  name: istio-installer
  apiGroup: rbac.authorization.k8s.io
